name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    name: PHPUnit with PHP ${{ matrix.php-version }} ${{ matrix.dependencies }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: "8.1"
            dependencies: "lowest"
          - php-version: "8.1"
            dependencies: "highest"
          - php-version: "8.2"
            dependencies: "highest"
          - php-version: "8.3"
            dependencies: "highest"
          - php-version: "8.4"
            dependencies: "highest"

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: PHP Setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug

      - name: Setup PHP problem matcher
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Setup PHPUnit problem matcher
        uses: mheap/phpunit-matcher-action@v1

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: Execute tests
        run: |
          composer tests:coverage:ci
          php .check-coverage.php
